baseURL = 'https://puthujjana.github.io/puthujjana/'
languageCode = 'en-us'
title = 'Puthujjana'
theme = 'mainroad'

ignoreLogs = ['warning-goldmark-raw-html']

[Params.sidebar]
home = "right"   # Sidebar for the homepage
list = "right"   # Sidebar for list pages (e.g., section and taxonomy pages)
single = "right" # Sidebar for single article pages
widgets = ["search", "recent", "categories", "taglist"]

