baseURL = 'https://puthujjana.github.io/puthujjana/'
languageCode = 'en-us'
title = 'Puthujjana'
theme = 'mainroad'

ignoreLogs = ['warning-goldmark-raw-html']

[params]
  disableThemeCredit = true

  [[params.widgets]]
    name = "search"

  [[params.widgets]]
    name = "recent"

  [[params.widgets]]
    name = "categories"

  [[params.widgets]]
    name = "tags"
