baseURL = 'https://puthujjana.github.io/puthujjana/'
languageCode = 'en-us'
title = 'Puthujjana'
theme = 'PaperMod'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[markup]
  [markup.goldmark.renderer]
    unsafe = true

[params]
  ShowArchive = true

[[menu.main]]
  name = "Archive"
  url = "archives/"
  weight = 10

[taxonomies]
  category = "categories"
  tag = "tags"

sectionPagesMenu = 'main'
