baseURL = 'https://puthujjana.github.io/puthujjana/'
languageCode = 'en-us'
title = 'Puthujjana'
theme = 'mainroad'

[Params.sidebar]
  home = "right"
  list = "right"
  single = "right"

[[Params.widgets]]
  name = "search"

[[Params.widgets]]
  name = "recent"

[[Params.widgets]]
  name = "categories"

[[Params.widgets]]
  name = "tags"

