baseURL = 'https://puthujjana.github.io/puthujjana/'
languageCode = 'en-us'
title = 'Puthujjana'
theme = 'PaperMod'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3
    ordered = false

sectionPagesMenu = 'main'
